;;; The sine of an angle (specified in radians) can be computed by making use of the approximation
;;; sin x ~= x if x is sufficiently small,
;;; and the trigonometric identity sin x = 3(sin x/3) - 4(sin x/3)^3
;;; to reduce the size of the argument of sin.
;;; For purposes of this exercise an angle is considered 'sufficiently small' if its magnitude is not greater than 0.1 radians.
;;; These ideas are incorporated in the following procedures:

#lang sicp

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

;;; a.  How many times is the procedure p applied when (sine 12.15) is evaluated?

;;; sin x ~= x for x <= 0.1
;;; Every step x = x / 3 if x > 0.1 or x if x <= 0.1
;;; x / (3 ^ n) <= 0.1 <= x / (3 ^ (n + 1))
;;; x = 12.5
;;; n = 4 | 12.5 / 3^4 | 12.5 / 81 > 0.1
;;; n = 5 | 12.5 / 3^5 | 12.5 / 243 < 0.1
;;; 5 steps


;;; b.  What is the order of growth in space and number of steps (as a function of a)
;;; used by the process generated by the sine procedure when (sine a) is evaluated?

;;; Every n-th step angle = angle / 3^n util angle <= 0.1
;;; angle / 3^n <= 0.1 | 3^n >= 10angle | n >= log (base 3, 10angle)
;;; Steps order of growth - O(log angle)
;;; Space order of growth is the same.

(sine 12.15)
(p (sine (/ angle 3.0))) ; 1
(p (sine (4.5)))
(p (p (sine (/ 4.5 3)))) ; 2
(p (p (sine 1.5)))
(p (p (p (sine (/ 1.5 3)))))
(p (p (p (sine 0.5))))
(p (p (p (p (sine (/ 0.5 3))))))
(p (p (p (p (sine 0.16666666666666666)))))
(p (p (p (p (p (sine (/ 0.16666666666666666 3)))))))
(p (p (p (p (p (sine 0.05555555555555555))))))
(p (p (p (p (p 0.05555555555555555)))))
(p (p (p (p 0.05555555555555555))))
(p (p (p 0.05555555555555555)))
(p (p 0.05555555555555555))
(p 0.05555555555555555)
0.05555555555555555
;;; 5 times